# Gradle JVM ayarlar?
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Android ayarlar?
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
android.nonTransitiveRClass=true

# Build optimizasyonu
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# R8 optimizasyonu
android.enableR8.fullMode=true